### ISSUE TITLE
Remove ::after and ::before for default box-sizing behaviour

### ISSUE THREAD

**Issue by kaij** [at-import/toolkit#29] opened 2013-08-01 15:58 UTC
I suggest the *::after and *::before pseudoclass selectors for box-sizing (in _border-box.scss) to be removed or made optional. They may lead to slow style recalculation on mobile platforms (I had this as an issue with iOS 6 in Safari). I think it's acceptable that when using these pseudoclasses that we can specify the box-sizing method seperately.

It's not such a big issue because we can just leave away the border-box includes, but it easily gets forgotten.

**Comment by Snugug** [comment] 2013-08-01 16:06
I will not remove it, as if you don't have it they won't get the border box.

If you can provide a reduced usecase that can show a marked performance reduction from this style rule, I'm open providing a variable configuration to choose to include it or not.

The easier thing to do, if you'd still like to be able to import all of Toolkit but have it not write any CSS, you can do `@import "toolkit-no-css"` instead.

**Comment by kaij** [comment] 2013-08-03 10:05
Ok, great. I think it's a more generic performance problem with CSS pseudoclasses on certain platforms. The problem is that it's very hard to provide actual numbers as you can only get the number of evaluations and not the time it took to evaluate (Safari Web Developer Profiling using external iOS device). If you have any suggestions on how to measure the actual evaluation time for CSS rules on mobile devices, I'm open - but otherwise I don't think it's worth the effort of proving something that's already solved by removing just the two pseudoclasses (I still think the \*  rule is useful).

For further reference, here is an older jquery ui bug with a similar problem (:active pseudoclass). http://bugs.jqueryui.com/ticket/6757.

Note: I was using the ftscroller library with this rule. The performance impact with the pseudoclasses might well depend on the number of evaluations that could be quite high when simulating scrolling.

**Comment by Snugug** [comment] 2013-08-03 10:53
Without a reduced test case proving it's a generic issue and not an extreme edge case caused by the intersection of other things and evidence beyond a single bug report and a three year old jQuery UI issue, I'm not willing to make an API and mental model backwards-incompatible change to Toolkit. Doubly so as this can be solved in multiple ways with Toolkit as it stands; you can either import [`toolkit-no-css`](https://github.com/Team-Sass/toolkit/blob/1.x.x/compass/stylesheets/_toolkit-no-css.scss) and write our own `border-box` selector while still getting the full Toolkit stack imported, or you can import [`box-sizing`](https://github.com/Team-Sass/toolkit/blob/1.x.x/compass/stylesheets/toolkit/_box-sizing.scss) individually and achieve the same results.

For these reasons, I'm going to close this thread.

**Closed as completed by Snugug** 2013-08-03 10:53 UTC
