### ISSUE TITLE
Support for Sass 3.4?

### ISSUE THREAD

**Issue by lolmaus** [at-import/toolkit#73] opened 2014-08-19 18:34 UTC
Toolkit has Sass locked at 3.3.

Can you bump the version?

**Comment by Snugug** [comment] 2014-08-19 18:35
Duplicate of #72

**Closed as completed by Snugug** 2014-08-19 18:35 UTC

**Comment by lolmaus** [comment] 2014-08-19 18:36
Sorry, i'm still not used that pull requests are now on a separate tab.

**Comment by Snugug** [comment] 2014-08-19 18:36
No worries
